[tool.commitizen]
name = "custy"
<<<<<<< HEAD
version = "1.10.15"
=======
version = "1.10.15"
>>>>>>> d0e738133a102efb3619aed7b3c95821d864f12d
tag_format = "v$version"
changelog_file = "CHANGELOG.md"
changelog_incremental = true
template = "./.cz_changelog.j2"

[tool.commitizen.bump_message]
major = "feat: bump: version $current_version → $new_version"
minor = "feat: bump: version $current_version → $new_version"
patch = "fix: bump: version $current_version → $new_version"
