# tests/core/git_ops/hooks/test_service.py

"""Tests for cross-platform Git commit-hook planning and execution."""

from pathlib import Path
from subprocess import CompletedProcess

import pytest

from app.core.git_ops.hooks import (
    GitHookMode,
    GitHookPolicyError,
    GitHookService,
    GitHookSettings,
    HookExecution,
)


def _git_path_fallback(command, **kwargs) -> CompletedProcess:
    """Force tests to use their temporary conventional .git/hooks path."""

    return CompletedProcess(command, 1, stdout="", stderr="not a repository")


def _write_hook(path: Path, content: bytes) -> None:
    """Create a hook fixture and make it executable where supported."""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    path.chmod(0o755)


class TestGitHookInspection:
    """Cover repositories with no hooks, pre-commit hooks, and custom hooks."""

    def test_auto_uses_native_git_when_project_has_no_hooks(self, tmp_path) -> None:
        """Projects that do not use pre-commit require no extra dependency."""

        service = GitHookService(
            project_root=tmp_path,
            platform_name="posix",
            command_runner=_git_path_fallback,
            executable_resolver=lambda _: None,
        )

        plan = service.inspect()

        assert plan.execution is HookExecution.NATIVE
        assert plan.stages == ()

    def test_auto_does_not_activate_config_without_installed_hook(
        self,
        tmp_path,
    ) -> None:
        """A config file alone does not change native Git behavior."""

        (tmp_path / ".pre-commit-config.yaml").write_text("repos: []\n")
        service = GitHookService(
            project_root=tmp_path,
            platform_name="posix",
            command_runner=_git_path_fallback,
            executable_resolver=lambda _: None,
        )

        assert service.inspect().execution is HookExecution.NATIVE

    def test_auto_adapts_recognized_windows_pre_commit_hook(self, tmp_path) -> None:
        """CRLF Windows wrappers use direct pre-commit inside Linux."""

        (tmp_path / ".pre-commit-config.yaml").write_text("repos: []\n")
        _write_hook(
            tmp_path / ".git" / "hooks" / "pre-commit",
            (
                b"#!/bin/sh\r\n"
                b"# File generated by pre-commit: https://pre-commit.com\r\n"
                b"ARGS=(hook-impl --hook-type=pre-commit)\r\n"
            ),
        )
        service = GitHookService(
            project_root=tmp_path,
            platform_name="posix",
            command_runner=_git_path_fallback,
            executable_resolver=lambda _: "/usr/bin/pre-commit",
        )

        plan = service.inspect()

        assert plan.execution is HookExecution.PRE_COMMIT
        assert plan.stages == ("pre-commit",)
        assert plan.requires_no_verify is True

    def test_auto_refuses_to_bypass_incompatible_custom_hook(self, tmp_path) -> None:
        """Unknown hooks remain user-owned and fail safely."""

        _write_hook(
            tmp_path / ".git" / "hooks" / "pre-commit",
            b"#!/bin/sh\r\necho custom\r\n",
        )
        service = GitHookService(
            project_root=tmp_path,
            platform_name="posix",
            command_runner=_git_path_fallback,
            executable_resolver=lambda _: "/usr/bin/pre-commit",
        )

        with pytest.raises(GitHookPolicyError, match="custom Git hook"):
            service.inspect()

    def test_native_mode_leaves_every_hook_to_git(self, tmp_path) -> None:
        """Explicit native mode performs no adaptation or dependency checks."""

        service = GitHookService(
            GitHookSettings(mode=GitHookMode.NATIVE),
            project_root=tmp_path,
            platform_name="posix",
            command_runner=_git_path_fallback,
            executable_resolver=lambda _: None,
        )

        assert service.inspect().execution is HookExecution.NATIVE

    def test_explicit_pre_commit_requires_configuration(self, tmp_path) -> None:
        """Direct mode cannot run without project pre-commit configuration."""

        service = GitHookService(
            GitHookSettings(mode=GitHookMode.PRE_COMMIT),
            project_root=tmp_path,
            command_runner=_git_path_fallback,
            executable_resolver=lambda _: "/usr/bin/pre-commit",
        )

        with pytest.raises(GitHookPolicyError, match="requires"):
            service.inspect()

    def test_explicit_pre_commit_refuses_unknown_installed_hook(
        self,
        tmp_path,
    ) -> None:
        """Explicit mode still cannot silently bypass a custom hook."""

        (tmp_path / ".pre-commit-config.yaml").write_text("repos: []\n")
        _write_hook(
            tmp_path / ".git" / "hooks" / "pre-commit",
            b"#!/bin/sh\necho custom\n",
        )
        service = GitHookService(
            GitHookSettings(mode=GitHookMode.PRE_COMMIT),
            project_root=tmp_path,
            command_runner=_git_path_fallback,
            executable_resolver=lambda _: "/usr/bin/pre-commit",
        )

        with pytest.raises(GitHookPolicyError, match="unknown custom"):
            service.inspect()


class TestGitHookExecution:
    """Validate the exact direct pre-commit command contract."""

    def test_runs_resolved_pre_commit_stage(self, tmp_path) -> None:
        """Direct execution runs the configured stage without a shell."""

        calls: list[list[str]] = []

        def runner(command, **kwargs) -> CompletedProcess:
            calls.append(command)
            return CompletedProcess(command, 0, stdout="Passed", stderr="")

        (tmp_path / ".pre-commit-config.yaml").write_text("repos: []\n")
        service = GitHookService(
            GitHookSettings(mode=GitHookMode.PRE_COMMIT),
            project_root=tmp_path,
            command_runner=runner,
            executable_resolver=lambda _: "/usr/bin/pre-commit",
        )
        plan = service.inspect()

        result = service.run(plan, message_file=None)

        assert result.success is True
        assert calls[-1] == [
            "/usr/bin/pre-commit",
            "run",
            "--hook-stage",
            "pre-commit",
        ]
