# app/core/git_ops/hooks/service.py

"""Inspect and execute commit hooks without silently weakening validation.

The service distinguishes repositories without hooks, compatible native Git
hooks, and pre-commit-generated wrappers that cannot run in the current
environment. In the last case it can invoke the same pre-commit stages
directly and tell the caller to bypass only the already-executed wrappers for
that one Git commit.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from collections.abc import Callable
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from app.core.git_ops.git.result import CommandResult

from .settings import GitHookMode, GitHookSettings

_BYPASSED_BY_NO_VERIFY = ("pre-commit", "commit-msg")
_PRE_COMMIT_MARKER = "File generated by pre-commit"


class HookExecution(StrEnum):
    """Resolved execution mechanism for the next Git commit."""

    NATIVE = "native"
    PRE_COMMIT = "pre_commit"


class GitHookPolicyError(RuntimeError):
    """Raised when configured hooks cannot be executed without bypassing them."""


@dataclass(frozen=True, slots=True)
class GitHookPlan:
    """Describe how the current commit hooks must be executed.

    Args:
        execution: Native Git execution or direct pre-commit execution.
        stages: Installed pre-commit stages that must run directly.
        reason: Human-readable reason for the resolved behavior.
    """

    execution: HookExecution = HookExecution.NATIVE
    stages: tuple[str, ...] = ()
    reason: str = "No incompatible commit hooks were detected."

    @property
    def requires_no_verify(self) -> bool:
        """Return whether Git must skip wrappers already executed directly."""

        return self.execution is HookExecution.PRE_COMMIT


class GitHookService:
    """Resolve and run safe cross-platform commit-hook behavior."""

    def __init__(
        self,
        settings: GitHookSettings | None = None,
        *,
        project_root: Path | None = None,
        platform_name: str | None = None,
        executable_resolver: Callable[[str], str | None] = shutil.which,
        command_runner: Callable[..., subprocess.CompletedProcess] = subprocess.run,
    ) -> None:
        """Initialize hook discovery dependencies.

        Args:
            settings: Validated project hook settings.
            project_root: Repository root. Defaults to the working directory.
            platform_name: Platform override used by tests.
            executable_resolver: Resolver for the ``pre-commit`` executable.
            command_runner: Subprocess-compatible command runner.
        """

        self.settings = settings or GitHookSettings()
        self.project_root = Path(project_root or Path.cwd()).resolve()
        self.platform_name = platform_name or os.name
        self.executable_resolver = executable_resolver
        self.command_runner = command_runner

    def inspect(self) -> GitHookPlan:
        """Resolve the safe hook plan for the current repository.

        Returns:
            Native execution for projects without relevant hooks, projects
            with compatible hooks, or explicit ``native`` mode. Returns direct
            pre-commit execution only when requested or when ``auto`` detects
            recognized incompatible pre-commit wrappers.

        Raises:
            GitHookPolicyError: If direct pre-commit execution is unavailable
                or would bypass an unknown/custom commit hook.
        """

        if self.settings.mode is GitHookMode.NATIVE:
            return GitHookPlan(reason="Native hook execution was explicitly selected.")

        hooks = {
            stage: path
            for stage in _BYPASSED_BY_NO_VERIFY
            if (path := self._resolve_hook_path(stage)).is_file()
        }

        if self.settings.mode is GitHookMode.AUTO and not hooks:
            return GitHookPlan(
                reason="No installed pre-commit or commit-msg hook was found."
            )

        if self.settings.mode is GitHookMode.PRE_COMMIT:
            unknown = [
                str(path)
                for path in hooks.values()
                if not self._is_pre_commit_managed(path)
            ]
            if unknown:
                raise GitHookPolicyError(
                    "Direct pre-commit mode would bypass an unknown custom Git "
                    "hook: " + ", ".join(unknown)
                )
            stages = tuple(
                stage
                for stage, path in hooks.items()
                if self._is_pre_commit_managed(path)
            )
            if not stages:
                stages = ("pre-commit",)
            self._require_pre_commit(stages)
            return GitHookPlan(
                execution=HookExecution.PRE_COMMIT,
                stages=stages,
                reason="Direct pre-commit execution was explicitly selected.",
            )

        incompatible = {
            stage: path for stage, path in hooks.items() if self._is_incompatible(path)
        }
        if not incompatible:
            return GitHookPlan(reason="Installed commit hooks are native-compatible.")

        unknown = [
            str(path)
            for path in hooks.values()
            if not self._is_pre_commit_managed(path)
        ]
        if unknown:
            raise GitHookPolicyError(
                "An incompatible custom Git hook cannot be adapted safely: "
                + ", ".join(unknown)
                + ". Repair the hook for this environment or select native mode."
            )

        stages = tuple(hooks)
        self._require_pre_commit(stages)
        return GitHookPlan(
            execution=HookExecution.PRE_COMMIT,
            stages=stages,
            reason=(
                "Recognized pre-commit wrapper is incompatible with the current "
                "environment; Custy will run its configured stages directly."
            ),
        )

    def run(self, plan: GitHookPlan, *, message_file: Path | None) -> CommandResult:
        """Execute every direct pre-commit stage in a resolved plan.

        Args:
            plan: Plan returned by :meth:`inspect`.
            message_file: Commit-message file required by ``commit-msg`` hooks.

        Returns:
            First failed result, or a successful combined result.

        Raises:
            GitHookPolicyError: If a commit-msg stage has no message file.
        """

        if plan.execution is HookExecution.NATIVE:
            return CommandResult(returncode=0)

        executable = self._require_pre_commit(plan.stages)
        combined_stdout: list[str] = []
        combined_stderr: list[str] = []

        for stage in plan.stages:
            command = [executable, "run", "--hook-stage", stage]
            if stage == "commit-msg":
                if message_file is None:
                    raise GitHookPolicyError(
                        "Direct commit-msg validation requires a commit-message file."
                    )
                command.extend(["--commit-msg-filename", str(message_file)])

            try:
                completed = self.command_runner(
                    command,
                    cwd=self.project_root,
                    check=False,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    encoding="utf-8",
                )
            except OSError as error:
                return CommandResult(returncode=1, stderr=str(error))

            stdout = completed.stdout or ""
            stderr = completed.stderr or ""
            combined_stdout.append(stdout)
            combined_stderr.append(stderr)
            if completed.returncode != 0:
                return CommandResult(
                    returncode=completed.returncode,
                    stdout=stdout,
                    stderr=stderr,
                )

        return CommandResult(
            returncode=0,
            stdout="\n".join(part for part in combined_stdout if part),
            stderr="\n".join(part for part in combined_stderr if part),
        )

    def _require_pre_commit(self, stages: tuple[str, ...]) -> str:
        """Return the pre-commit executable or raise an actionable error."""

        config_path = self.project_root / ".pre-commit-config.yaml"
        if not config_path.is_file():
            raise GitHookPolicyError(
                "Direct pre-commit execution requires .pre-commit-config.yaml."
            )

        executable = self.executable_resolver("pre-commit")
        if executable is None:
            stage_text = ", ".join(stages)
            raise GitHookPolicyError(
                "The pre-commit executable is unavailable for required stage(s): "
                f"{stage_text}. Install `custy[hooks]` or use a Custy image that "
                "includes hook support."
            )
        return executable

    def _resolve_hook_path(self, stage: str) -> Path:
        """Resolve a hook path through Git, with a conventional fallback."""

        try:
            completed = self.command_runner(
                ["git", "rev-parse", "--git-path", f"hooks/{stage}"],
                cwd=self.project_root,
                check=False,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                encoding="utf-8",
            )
        except OSError:
            completed = None

        if completed is not None and completed.returncode == 0:
            raw_path = (completed.stdout or "").strip()
            if raw_path:
                path = Path(raw_path)
                if not path.is_absolute():
                    path = self.project_root / path
                return path.resolve()

        return (self.project_root / ".git" / "hooks" / stage).resolve()

    @staticmethod
    def _is_pre_commit_managed(path: Path) -> bool:
        """Return whether a hook contains pre-commit's generated marker."""

        try:
            return _PRE_COMMIT_MARKER in path.read_text(
                encoding="utf-8",
                errors="replace",
            )
        except OSError:
            return False

    def _is_incompatible(self, path: Path) -> bool:
        """Return whether a hook wrapper cannot execute on this platform."""

        if self.platform_name == "nt":
            return False

        try:
            content = path.read_bytes()
        except OSError:
            return True

        first_line = content.split(b"\n", 1)[0]
        if first_line.endswith(b"\r"):
            return True

        decoded = content.decode("utf-8", errors="replace")
        if first_line.rstrip(b"\r") == b"#!/bin/sh" and "ARGS=(" in decoded:
            return True

        return not os.access(path, os.X_OK)
